---
- name: Ensure ~/.config exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: "0755"

- name: Deploy Starship config
  ansible.builtin.copy:
    src: starship/starship.toml
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    mode: "0644"
