- name: Install Kustomize from official install script
  become: true
  shell: |
    curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
    mv kustomize /usr/local/bin/kustomize
  args:
    chdir: /tmp
    creates: /usr/local/bin/kustomize