- name: Load Node.js vars
  ansible.builtin.include_vars: ../../vars/nodejs.yml

- name: Tasks for nodejs
  ansible.builtin.include_role:
    name: geerlingguy.nodejs
  vars:
    ansible_become: true

- name: Setup pnpm global environment
  command: pnpm setup
  become: false

- name: Install global pnpm packages
  shell: |
    source ~/.zshrc
    pnpm add -g {{ item }}
  args:
    executable: /bin/zsh
  loop: "{{ nodejs_pnpm_global_packages }}"
  become: false